#include <ft2build.h>
#include FT_FREETYPE_H

#include <lua.h>

static void set_integer_constant(lua_State *L, const char *name,
                                 lua_Integer value) {
  lua_pushinteger(L, value);
  lua_setfield(L, -2, name);
}

#define SET_LONG_CONST(name) set_integer_constant(L, #name, (lua_Integer)FT_##name)

void rig_register_freetype(lua_State *L) {
  SET_LONG_CONST(FACE_FLAG_SCALABLE);
  SET_LONG_CONST(FACE_FLAG_FIXED_SIZES);
  SET_LONG_CONST(FACE_FLAG_FIXED_WIDTH);
  SET_LONG_CONST(FACE_FLAG_SFNT);
  SET_LONG_CONST(FACE_FLAG_HORIZONTAL);
  SET_LONG_CONST(FACE_FLAG_VERTICAL);
  SET_LONG_CONST(FACE_FLAG_KERNING);
  SET_LONG_CONST(FACE_FLAG_COLOR);

  SET_LONG_CONST(STYLE_FLAG_ITALIC);
  SET_LONG_CONST(STYLE_FLAG_BOLD);

  SET_LONG_CONST(LOAD_DEFAULT);
  SET_LONG_CONST(LOAD_NO_SCALE);
  SET_LONG_CONST(LOAD_NO_HINTING);
  SET_LONG_CONST(LOAD_RENDER);
  SET_LONG_CONST(LOAD_NO_BITMAP);
  SET_LONG_CONST(LOAD_VERTICAL_LAYOUT);
  SET_LONG_CONST(LOAD_FORCE_AUTOHINT);
  SET_LONG_CONST(LOAD_CROP_BITMAP);
  SET_LONG_CONST(LOAD_PEDANTIC);
  SET_LONG_CONST(LOAD_IGNORE_GLOBAL_ADVANCE_WIDTH);
  SET_LONG_CONST(LOAD_NO_RECURSE);
  SET_LONG_CONST(LOAD_IGNORE_TRANSFORM);
  SET_LONG_CONST(LOAD_MONOCHROME);
  SET_LONG_CONST(LOAD_LINEAR_DESIGN);
  SET_LONG_CONST(LOAD_NO_AUTOHINT);
  SET_LONG_CONST(LOAD_COLOR);
  SET_LONG_CONST(LOAD_COMPUTE_METRICS);
  SET_LONG_CONST(LOAD_BITMAP_METRICS_ONLY);
  SET_LONG_CONST(LOAD_ADVANCE_ONLY);
  SET_LONG_CONST(LOAD_TARGET_NORMAL);
  SET_LONG_CONST(LOAD_TARGET_LIGHT);
  SET_LONG_CONST(LOAD_TARGET_MONO);
  SET_LONG_CONST(LOAD_TARGET_LCD);
  SET_LONG_CONST(LOAD_TARGET_LCD_V);

  SET_LONG_CONST(RENDER_MODE_NORMAL);
  SET_LONG_CONST(RENDER_MODE_LIGHT);
  SET_LONG_CONST(RENDER_MODE_MONO);
  SET_LONG_CONST(RENDER_MODE_LCD);
  SET_LONG_CONST(RENDER_MODE_LCD_V);
  SET_LONG_CONST(RENDER_MODE_SDF);

  SET_LONG_CONST(PIXEL_MODE_NONE);
  SET_LONG_CONST(PIXEL_MODE_MONO);
  SET_LONG_CONST(PIXEL_MODE_GRAY);
  SET_LONG_CONST(PIXEL_MODE_GRAY2);
  SET_LONG_CONST(PIXEL_MODE_GRAY4);
  SET_LONG_CONST(PIXEL_MODE_LCD);
  SET_LONG_CONST(PIXEL_MODE_LCD_V);
  SET_LONG_CONST(PIXEL_MODE_BGRA);

  SET_LONG_CONST(KERNING_DEFAULT);
  SET_LONG_CONST(KERNING_UNFITTED);
  SET_LONG_CONST(KERNING_UNSCALED);
}
