#include <GL/glcorearb.h>

#include <lua.h>

static void set_u32_constant(lua_State *L, const char *name, unsigned int value) {
  lua_pushinteger(L, (lua_Integer)value);
  lua_setfield(L, -2, name);
}

#define SET_GL_CONST(name) set_u32_constant(L, #name, GL_##name)

void rig_register_gl(lua_State *L) {
  SET_GL_CONST(FALSE);
  SET_GL_CONST(TRUE);

  SET_GL_CONST(VERSION);
  SET_GL_CONST(COLOR_BUFFER_BIT);
  SET_GL_CONST(DEPTH_BUFFER_BIT);
  SET_GL_CONST(BLEND);
  SET_GL_CONST(FLOAT);
  SET_GL_CONST(TRIANGLES);
  SET_GL_CONST(ARRAY_BUFFER);
  SET_GL_CONST(STATIC_DRAW);
  SET_GL_CONST(DYNAMIC_DRAW);
  SET_GL_CONST(TEXTURE_2D);
  SET_GL_CONST(TEXTURE0);
  SET_GL_CONST(TEXTURE_MIN_FILTER);
  SET_GL_CONST(TEXTURE_MAG_FILTER);
  SET_GL_CONST(TEXTURE_WRAP_S);
  SET_GL_CONST(TEXTURE_WRAP_T);
  SET_GL_CONST(CLAMP_TO_EDGE);
  SET_GL_CONST(LINEAR);
  SET_GL_CONST(RGBA);
  SET_GL_CONST(UNSIGNED_BYTE);
  SET_GL_CONST(SRC_ALPHA);
  SET_GL_CONST(ONE_MINUS_SRC_ALPHA);
  SET_GL_CONST(VERTEX_SHADER);
  SET_GL_CONST(FRAGMENT_SHADER);
#ifdef GL_COMPUTE_SHADER
  SET_GL_CONST(COMPUTE_SHADER);
#endif
  SET_GL_CONST(COMPILE_STATUS);
  SET_GL_CONST(LINK_STATUS);
  SET_GL_CONST(INFO_LOG_LENGTH);
  SET_GL_CONST(DEPTH_TEST);
  SET_GL_CONST(LEQUAL);
}
