#include <SDL3/SDL.h>

#include <lua.h>

static void set_u32_constant(lua_State *L, const char *name, Uint32 value) {
  lua_pushinteger(L, (lua_Integer)value);
  lua_setfield(L, -2, name);
}

static void set_string_constant(lua_State *L, const char *name,
                                const char *value) {
  lua_pushstring(L, value);
  lua_setfield(L, -2, name);
}

#define SET_U32_CONST(name) set_u32_constant(L, #name, SDL_##name)
#define SET_INIT_CONST(name) set_u32_constant(L, "INIT_" #name, SDL_INIT_##name)
#define SET_PROP_CONST(name) set_string_constant(L, #name, SDL_##name)

void rig_register_sdl3(lua_State *L) {
  SET_U32_CONST(KMOD_SHIFT);
  SET_U32_CONST(KMOD_CTRL);
  SET_U32_CONST(KMOD_ALT);
  SET_U32_CONST(KMOD_GUI);

  SET_U32_CONST(GPU_SHADERFORMAT_INVALID);
  SET_U32_CONST(GPU_SHADERFORMAT_PRIVATE);
  SET_U32_CONST(GPU_SHADERFORMAT_SPIRV);
  SET_U32_CONST(GPU_SHADERFORMAT_DXBC);
  SET_U32_CONST(GPU_SHADERFORMAT_DXIL);
  SET_U32_CONST(GPU_SHADERFORMAT_MSL);
  SET_U32_CONST(GPU_SHADERFORMAT_METALLIB);

  SET_U32_CONST(GPU_SHADERSTAGE_VERTEX);
  SET_U32_CONST(GPU_SHADERSTAGE_FRAGMENT);

  SET_U32_CONST(GPU_PRIMITIVETYPE_TRIANGLELIST);
  SET_U32_CONST(GPU_PRIMITIVETYPE_TRIANGLESTRIP);

  SET_U32_CONST(GPU_LOADOP_LOAD);
  SET_U32_CONST(GPU_LOADOP_CLEAR);
  SET_U32_CONST(GPU_LOADOP_DONT_CARE);

  SET_U32_CONST(GPU_STOREOP_STORE);
  SET_U32_CONST(GPU_STOREOP_DONT_CARE);
  SET_U32_CONST(GPU_STOREOP_RESOLVE);
  SET_U32_CONST(GPU_STOREOP_RESOLVE_AND_STORE);

  SET_U32_CONST(GPU_INDEXELEMENTSIZE_16BIT);
  SET_U32_CONST(GPU_INDEXELEMENTSIZE_32BIT);

  SET_U32_CONST(GPU_TEXTUREFORMAT_INVALID);
  SET_U32_CONST(GPU_TEXTUREFORMAT_D16_UNORM);
  SET_U32_CONST(GPU_TEXTUREFORMAT_D24_UNORM);
  SET_U32_CONST(GPU_TEXTUREFORMAT_D32_FLOAT);
  SET_U32_CONST(GPU_TEXTUREFORMAT_D24_UNORM_S8_UINT);
  SET_U32_CONST(GPU_TEXTUREFORMAT_D32_FLOAT_S8_UINT);

  SET_U32_CONST(GPU_TEXTUREUSAGE_SAMPLER);
  SET_U32_CONST(GPU_TEXTUREUSAGE_COLOR_TARGET);
  SET_U32_CONST(GPU_TEXTUREUSAGE_DEPTH_STENCIL_TARGET);
  SET_U32_CONST(GPU_TEXTUREUSAGE_GRAPHICS_STORAGE_READ);
  SET_U32_CONST(GPU_TEXTUREUSAGE_COMPUTE_STORAGE_READ);
  SET_U32_CONST(GPU_TEXTUREUSAGE_COMPUTE_STORAGE_WRITE);
  SET_U32_CONST(GPU_TEXTUREUSAGE_COMPUTE_STORAGE_SIMULTANEOUS_READ_WRITE);

  SET_U32_CONST(GPU_TEXTURETYPE_2D);
  SET_U32_CONST(GPU_TEXTURETYPE_2D_ARRAY);
  SET_U32_CONST(GPU_TEXTURETYPE_3D);
  SET_U32_CONST(GPU_TEXTURETYPE_CUBE);
  SET_U32_CONST(GPU_TEXTURETYPE_CUBE_ARRAY);

  SET_U32_CONST(GPU_SAMPLECOUNT_1);
  SET_U32_CONST(GPU_SAMPLECOUNT_2);
  SET_U32_CONST(GPU_SAMPLECOUNT_4);
  SET_U32_CONST(GPU_SAMPLECOUNT_8);

  SET_U32_CONST(GPU_BUFFERUSAGE_VERTEX);
  SET_U32_CONST(GPU_BUFFERUSAGE_INDEX);
  SET_U32_CONST(GPU_BUFFERUSAGE_INDIRECT);
  SET_U32_CONST(GPU_BUFFERUSAGE_GRAPHICS_STORAGE_READ);
  SET_U32_CONST(GPU_BUFFERUSAGE_COMPUTE_STORAGE_READ);
  SET_U32_CONST(GPU_BUFFERUSAGE_COMPUTE_STORAGE_WRITE);

  SET_U32_CONST(GPU_TRANSFERBUFFERUSAGE_UPLOAD);
  SET_U32_CONST(GPU_TRANSFERBUFFERUSAGE_DOWNLOAD);

  SET_U32_CONST(GPU_VERTEXELEMENTFORMAT_FLOAT);
  SET_U32_CONST(GPU_VERTEXELEMENTFORMAT_FLOAT2);
  SET_U32_CONST(GPU_VERTEXELEMENTFORMAT_FLOAT3);
  SET_U32_CONST(GPU_VERTEXELEMENTFORMAT_FLOAT4);

  SET_U32_CONST(GPU_VERTEXINPUTRATE_VERTEX);
  SET_U32_CONST(GPU_VERTEXINPUTRATE_INSTANCE);

  SET_U32_CONST(GPU_FILLMODE_FILL);
  SET_U32_CONST(GPU_FILLMODE_LINE);

  SET_U32_CONST(GPU_CULLMODE_NONE);
  SET_U32_CONST(GPU_CULLMODE_FRONT);
  SET_U32_CONST(GPU_CULLMODE_BACK);

  SET_U32_CONST(GPU_FRONTFACE_COUNTER_CLOCKWISE);
  SET_U32_CONST(GPU_FRONTFACE_CLOCKWISE);

  SET_U32_CONST(GPU_COMPAREOP_INVALID);
  SET_U32_CONST(GPU_COMPAREOP_NEVER);
  SET_U32_CONST(GPU_COMPAREOP_LESS);
  SET_U32_CONST(GPU_COMPAREOP_EQUAL);
  SET_U32_CONST(GPU_COMPAREOP_LESS_OR_EQUAL);
  SET_U32_CONST(GPU_COMPAREOP_GREATER);
  SET_U32_CONST(GPU_COMPAREOP_NOT_EQUAL);
  SET_U32_CONST(GPU_COMPAREOP_GREATER_OR_EQUAL);
  SET_U32_CONST(GPU_COMPAREOP_ALWAYS);

  SET_U32_CONST(GPU_PRESENTMODE_VSYNC);
  SET_U32_CONST(GPU_PRESENTMODE_IMMEDIATE);
  SET_U32_CONST(GPU_PRESENTMODE_MAILBOX);

  SET_U32_CONST(GPU_SWAPCHAINCOMPOSITION_SDR);
  SET_U32_CONST(GPU_SWAPCHAINCOMPOSITION_SDR_LINEAR);
  SET_U32_CONST(GPU_SWAPCHAINCOMPOSITION_HDR_EXTENDED_LINEAR);
  SET_U32_CONST(GPU_SWAPCHAINCOMPOSITION_HDR10_ST2084);

  SET_INIT_CONST(AUDIO);
  SET_INIT_CONST(VIDEO);
  SET_INIT_CONST(JOYSTICK);
  SET_INIT_CONST(HAPTIC);
  SET_INIT_CONST(GAMEPAD);
  SET_INIT_CONST(EVENTS);
  SET_INIT_CONST(SENSOR);
  SET_INIT_CONST(CAMERA);

  /* APP_METADATA */
  SET_PROP_CONST(PROP_APP_METADATA_COPYRIGHT_STRING);
  SET_PROP_CONST(PROP_APP_METADATA_CREATOR_STRING);
  SET_PROP_CONST(PROP_APP_METADATA_IDENTIFIER_STRING);
  SET_PROP_CONST(PROP_APP_METADATA_NAME_STRING);
  SET_PROP_CONST(PROP_APP_METADATA_TYPE_STRING);
  SET_PROP_CONST(PROP_APP_METADATA_URL_STRING);
  SET_PROP_CONST(PROP_APP_METADATA_VERSION_STRING);

  /* AUDIOSTREAM_AUTO */
  SET_PROP_CONST(PROP_AUDIOSTREAM_AUTO_CLEANUP_BOOLEAN);

  /* DISPLAY_HDR */
  SET_PROP_CONST(PROP_DISPLAY_HDR_ENABLED_BOOLEAN);

  /* DISPLAY_KMSDRM */
  SET_PROP_CONST(PROP_DISPLAY_KMSDRM_PANEL_ORIENTATION_NUMBER);

  /* DISPLAY_WAYLAND */
  SET_PROP_CONST(PROP_DISPLAY_WAYLAND_WL_OUTPUT_POINTER);

  /* DISPLAY_WINDOWS */
  SET_PROP_CONST(PROP_DISPLAY_WINDOWS_HMONITOR_POINTER);

  /* FILE_DIALOG */
  SET_PROP_CONST(PROP_FILE_DIALOG_ACCEPT_STRING);
  SET_PROP_CONST(PROP_FILE_DIALOG_CANCEL_STRING);
  SET_PROP_CONST(PROP_FILE_DIALOG_FILTERS_POINTER);
  SET_PROP_CONST(PROP_FILE_DIALOG_LOCATION_STRING);
  SET_PROP_CONST(PROP_FILE_DIALOG_MANY_BOOLEAN);
  SET_PROP_CONST(PROP_FILE_DIALOG_NFILTERS_NUMBER);
  SET_PROP_CONST(PROP_FILE_DIALOG_TITLE_STRING);
  SET_PROP_CONST(PROP_FILE_DIALOG_WINDOW_POINTER);

  /* GLOBAL_VIDEO */
  SET_PROP_CONST(PROP_GLOBAL_VIDEO_WAYLAND_WL_DISPLAY_POINTER);

  /* GPU_BUFFER */
  SET_PROP_CONST(PROP_GPU_BUFFER_CREATE_NAME_STRING);

  /* GPU_COMPUTEPIPELINE */
  SET_PROP_CONST(PROP_GPU_COMPUTEPIPELINE_CREATE_NAME_STRING);

  /* GPU_DEVICE */
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_D3D12_AGILITY_SDK_PATH_STRING);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_D3D12_AGILITY_SDK_VERSION_NUMBER);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_D3D12_ALLOW_FEWER_RESOURCE_SLOTS_BOOLEAN);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_D3D12_SEMANTIC_NAME_STRING);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_DEBUGMODE_BOOLEAN);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_FEATURE_ANISOTROPY_BOOLEAN);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_FEATURE_CLIP_DISTANCE_BOOLEAN);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_FEATURE_DEPTH_CLAMPING_BOOLEAN);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_FEATURE_INDIRECT_DRAW_FIRST_INSTANCE_BOOLEAN);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_METAL_ALLOW_MACFAMILY1_BOOLEAN);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_NAME_STRING);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_PREFERLOWPOWER_BOOLEAN);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_SHADERS_DXBC_BOOLEAN);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_SHADERS_DXIL_BOOLEAN);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_SHADERS_METALLIB_BOOLEAN);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_SHADERS_MSL_BOOLEAN);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_SHADERS_PRIVATE_BOOLEAN);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_SHADERS_SPIRV_BOOLEAN);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_VERBOSE_BOOLEAN);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_VULKAN_OPTIONS_POINTER);
  SET_PROP_CONST(PROP_GPU_DEVICE_CREATE_VULKAN_REQUIRE_HARDWARE_ACCELERATION_BOOLEAN);
  SET_PROP_CONST(PROP_GPU_DEVICE_DRIVER_INFO_STRING);
  SET_PROP_CONST(PROP_GPU_DEVICE_DRIVER_NAME_STRING);
  SET_PROP_CONST(PROP_GPU_DEVICE_DRIVER_VERSION_STRING);
  SET_PROP_CONST(PROP_GPU_DEVICE_NAME_STRING);

  /* GPU_GRAPHICSPIPELINE */
  SET_PROP_CONST(PROP_GPU_GRAPHICSPIPELINE_CREATE_NAME_STRING);

  /* GPU_SAMPLER */
  SET_PROP_CONST(PROP_GPU_SAMPLER_CREATE_NAME_STRING);

  /* GPU_SHADER */
  SET_PROP_CONST(PROP_GPU_SHADER_CREATE_NAME_STRING);

  /* GPU_TEXTURE */
  SET_PROP_CONST(PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_A_FLOAT);
  SET_PROP_CONST(PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_B_FLOAT);
  SET_PROP_CONST(PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_DEPTH_FLOAT);
  SET_PROP_CONST(PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_G_FLOAT);
  SET_PROP_CONST(PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_R_FLOAT);
  SET_PROP_CONST(PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_STENCIL_NUMBER);
  SET_PROP_CONST(PROP_GPU_TEXTURE_CREATE_NAME_STRING);

  /* GPU_TRANSFERBUFFER */
  SET_PROP_CONST(PROP_GPU_TRANSFERBUFFER_CREATE_NAME_STRING);

  /* HIDAPI_LIBUSB */
  SET_PROP_CONST(PROP_HIDAPI_LIBUSB_DEVICE_HANDLE_POINTER);

  /* IOSTREAM_ANDROID */
  SET_PROP_CONST(PROP_IOSTREAM_ANDROID_AASSET_POINTER);

  /* IOSTREAM_DYNAMIC */
  SET_PROP_CONST(PROP_IOSTREAM_DYNAMIC_CHUNKSIZE_NUMBER);
  SET_PROP_CONST(PROP_IOSTREAM_DYNAMIC_MEMORY_POINTER);

  /* IOSTREAM_FILE */
  SET_PROP_CONST(PROP_IOSTREAM_FILE_DESCRIPTOR_NUMBER);

  /* IOSTREAM_MEMORY */
  SET_PROP_CONST(PROP_IOSTREAM_MEMORY_FREE_FUNC_POINTER);
  SET_PROP_CONST(PROP_IOSTREAM_MEMORY_POINTER);
  SET_PROP_CONST(PROP_IOSTREAM_MEMORY_SIZE_NUMBER);

  /* IOSTREAM_STDIO */
  SET_PROP_CONST(PROP_IOSTREAM_STDIO_FILE_POINTER);

  /* IOSTREAM_WINDOWS */
  SET_PROP_CONST(PROP_IOSTREAM_WINDOWS_HANDLE_POINTER);

  /* JOYSTICK_CAP */
  SET_PROP_CONST(PROP_JOYSTICK_CAP_MONO_LED_BOOLEAN);
  SET_PROP_CONST(PROP_JOYSTICK_CAP_PLAYER_LED_BOOLEAN);
  SET_PROP_CONST(PROP_JOYSTICK_CAP_RGB_LED_BOOLEAN);
  SET_PROP_CONST(PROP_JOYSTICK_CAP_RUMBLE_BOOLEAN);
  SET_PROP_CONST(PROP_JOYSTICK_CAP_TRIGGER_RUMBLE_BOOLEAN);

  /* NAME_STRING */
  SET_PROP_CONST(PROP_NAME_STRING);

  /* PROCESS_BACKGROUND */
  SET_PROP_CONST(PROP_PROCESS_BACKGROUND_BOOLEAN);

  /* PROCESS_CREATE */
  SET_PROP_CONST(PROP_PROCESS_CREATE_ARGS_POINTER);
  SET_PROP_CONST(PROP_PROCESS_CREATE_BACKGROUND_BOOLEAN);
  SET_PROP_CONST(PROP_PROCESS_CREATE_CMDLINE_STRING);
  SET_PROP_CONST(PROP_PROCESS_CREATE_ENVIRONMENT_POINTER);
  SET_PROP_CONST(PROP_PROCESS_CREATE_STDERR_NUMBER);
  SET_PROP_CONST(PROP_PROCESS_CREATE_STDERR_POINTER);
  SET_PROP_CONST(PROP_PROCESS_CREATE_STDERR_TO_STDOUT_BOOLEAN);
  SET_PROP_CONST(PROP_PROCESS_CREATE_STDIN_NUMBER);
  SET_PROP_CONST(PROP_PROCESS_CREATE_STDIN_POINTER);
  SET_PROP_CONST(PROP_PROCESS_CREATE_STDOUT_NUMBER);
  SET_PROP_CONST(PROP_PROCESS_CREATE_STDOUT_POINTER);
  SET_PROP_CONST(PROP_PROCESS_CREATE_WORKING_DIRECTORY_STRING);

  /* PROCESS_PID */
  SET_PROP_CONST(PROP_PROCESS_PID_NUMBER);

  /* PROCESS_STDERR */
  SET_PROP_CONST(PROP_PROCESS_STDERR_POINTER);

  /* PROCESS_STDIN */
  SET_PROP_CONST(PROP_PROCESS_STDIN_POINTER);

  /* PROCESS_STDOUT */
  SET_PROP_CONST(PROP_PROCESS_STDOUT_POINTER);

  /* RENDERER_CREATE */
  SET_PROP_CONST(PROP_RENDERER_CREATE_GPU_DEVICE_POINTER);
  SET_PROP_CONST(PROP_RENDERER_CREATE_GPU_SHADERS_DXIL_BOOLEAN);
  SET_PROP_CONST(PROP_RENDERER_CREATE_GPU_SHADERS_MSL_BOOLEAN);
  SET_PROP_CONST(PROP_RENDERER_CREATE_GPU_SHADERS_SPIRV_BOOLEAN);
  SET_PROP_CONST(PROP_RENDERER_CREATE_NAME_STRING);
  SET_PROP_CONST(PROP_RENDERER_CREATE_OUTPUT_COLORSPACE_NUMBER);
  SET_PROP_CONST(PROP_RENDERER_CREATE_PRESENT_VSYNC_NUMBER);
  SET_PROP_CONST(PROP_RENDERER_CREATE_SURFACE_POINTER);
  SET_PROP_CONST(PROP_RENDERER_CREATE_VULKAN_DEVICE_POINTER);
  SET_PROP_CONST(PROP_RENDERER_CREATE_VULKAN_GRAPHICS_QUEUE_FAMILY_INDEX_NUMBER);
  SET_PROP_CONST(PROP_RENDERER_CREATE_VULKAN_INSTANCE_POINTER);
  SET_PROP_CONST(PROP_RENDERER_CREATE_VULKAN_PHYSICAL_DEVICE_POINTER);
  SET_PROP_CONST(PROP_RENDERER_CREATE_VULKAN_PRESENT_QUEUE_FAMILY_INDEX_NUMBER);
  SET_PROP_CONST(PROP_RENDERER_CREATE_VULKAN_SURFACE_NUMBER);
  SET_PROP_CONST(PROP_RENDERER_CREATE_WINDOW_POINTER);

  /* RENDERER_D3D11 */
  SET_PROP_CONST(PROP_RENDERER_D3D11_DEVICE_POINTER);
  SET_PROP_CONST(PROP_RENDERER_D3D11_SWAPCHAIN_POINTER);

  /* RENDERER_D3D12 */
  SET_PROP_CONST(PROP_RENDERER_D3D12_COMMAND_QUEUE_POINTER);
  SET_PROP_CONST(PROP_RENDERER_D3D12_DEVICE_POINTER);
  SET_PROP_CONST(PROP_RENDERER_D3D12_SWAPCHAIN_POINTER);

  /* RENDERER_D3D9 */
  SET_PROP_CONST(PROP_RENDERER_D3D9_DEVICE_POINTER);

  /* RENDERER_GPU */
  SET_PROP_CONST(PROP_RENDERER_GPU_DEVICE_POINTER);

  /* RENDERER_HDR */
  SET_PROP_CONST(PROP_RENDERER_HDR_ENABLED_BOOLEAN);
  SET_PROP_CONST(PROP_RENDERER_HDR_HEADROOM_FLOAT);

  /* RENDERER_MAX */
  SET_PROP_CONST(PROP_RENDERER_MAX_TEXTURE_SIZE_NUMBER);

  /* RENDERER_NAME */
  SET_PROP_CONST(PROP_RENDERER_NAME_STRING);

  /* RENDERER_OUTPUT */
  SET_PROP_CONST(PROP_RENDERER_OUTPUT_COLORSPACE_NUMBER);

  /* RENDERER_SDR */
  SET_PROP_CONST(PROP_RENDERER_SDR_WHITE_POINT_FLOAT);

  /* RENDERER_SURFACE */
  SET_PROP_CONST(PROP_RENDERER_SURFACE_POINTER);

  /* RENDERER_TEXTURE */
  SET_PROP_CONST(PROP_RENDERER_TEXTURE_FORMATS_POINTER);
  SET_PROP_CONST(PROP_RENDERER_TEXTURE_WRAPPING_BOOLEAN);

  /* RENDERER_VSYNC */
  SET_PROP_CONST(PROP_RENDERER_VSYNC_NUMBER);

  /* RENDERER_VULKAN */
  SET_PROP_CONST(PROP_RENDERER_VULKAN_DEVICE_POINTER);
  SET_PROP_CONST(PROP_RENDERER_VULKAN_GRAPHICS_QUEUE_FAMILY_INDEX_NUMBER);
  SET_PROP_CONST(PROP_RENDERER_VULKAN_INSTANCE_POINTER);
  SET_PROP_CONST(PROP_RENDERER_VULKAN_PHYSICAL_DEVICE_POINTER);
  SET_PROP_CONST(PROP_RENDERER_VULKAN_PRESENT_QUEUE_FAMILY_INDEX_NUMBER);
  SET_PROP_CONST(PROP_RENDERER_VULKAN_SURFACE_NUMBER);
  SET_PROP_CONST(PROP_RENDERER_VULKAN_SWAPCHAIN_IMAGE_COUNT_NUMBER);

  /* RENDERER_WINDOW */
  SET_PROP_CONST(PROP_RENDERER_WINDOW_POINTER);

  /* SURFACE_HDR */
  SET_PROP_CONST(PROP_SURFACE_HDR_HEADROOM_FLOAT);

  /* SURFACE_HOTSPOT */
  SET_PROP_CONST(PROP_SURFACE_HOTSPOT_X_NUMBER);
  SET_PROP_CONST(PROP_SURFACE_HOTSPOT_Y_NUMBER);

  /* SURFACE_ROTATION */
  SET_PROP_CONST(PROP_SURFACE_ROTATION_FLOAT);

  /* SURFACE_SDR */
  SET_PROP_CONST(PROP_SURFACE_SDR_WHITE_POINT_FLOAT);

  /* SURFACE_TONEMAP */
  SET_PROP_CONST(PROP_SURFACE_TONEMAP_OPERATOR_STRING);

  /* TEXTINPUT_ANDROID */
  SET_PROP_CONST(PROP_TEXTINPUT_ANDROID_INPUTTYPE_NUMBER);

  /* TEXTINPUT_AUTOCORRECT */
  SET_PROP_CONST(PROP_TEXTINPUT_AUTOCORRECT_BOOLEAN);

  /* TEXTINPUT_CAPITALIZATION */
  SET_PROP_CONST(PROP_TEXTINPUT_CAPITALIZATION_NUMBER);

  /* TEXTINPUT_MULTILINE */
  SET_PROP_CONST(PROP_TEXTINPUT_MULTILINE_BOOLEAN);

  /* TEXTINPUT_TYPE */
  SET_PROP_CONST(PROP_TEXTINPUT_TYPE_NUMBER);

  /* TEXTURE_ACCESS */
  SET_PROP_CONST(PROP_TEXTURE_ACCESS_NUMBER);

  /* TEXTURE_COLORSPACE */
  SET_PROP_CONST(PROP_TEXTURE_COLORSPACE_NUMBER);

  /* TEXTURE_CREATE */
  SET_PROP_CONST(PROP_TEXTURE_CREATE_ACCESS_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_COLORSPACE_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_D3D11_TEXTURE_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_D3D11_TEXTURE_U_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_D3D11_TEXTURE_V_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_D3D12_TEXTURE_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_D3D12_TEXTURE_U_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_D3D12_TEXTURE_V_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_FORMAT_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_GPU_TEXTURE_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_GPU_TEXTURE_UV_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_GPU_TEXTURE_U_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_GPU_TEXTURE_V_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_HDR_HEADROOM_FLOAT);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_HEIGHT_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_METAL_PIXELBUFFER_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_UV_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_U_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_V_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_OPENGL_TEXTURE_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_OPENGL_TEXTURE_UV_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_OPENGL_TEXTURE_U_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_OPENGL_TEXTURE_V_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_PALETTE_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_SDR_WHITE_POINT_FLOAT);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_VULKAN_LAYOUT_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_VULKAN_TEXTURE_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_CREATE_WIDTH_NUMBER);

  /* TEXTURE_D3D11 */
  SET_PROP_CONST(PROP_TEXTURE_D3D11_TEXTURE_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_D3D11_TEXTURE_U_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_D3D11_TEXTURE_V_POINTER);

  /* TEXTURE_D3D12 */
  SET_PROP_CONST(PROP_TEXTURE_D3D12_TEXTURE_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_D3D12_TEXTURE_U_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_D3D12_TEXTURE_V_POINTER);

  /* TEXTURE_FORMAT */
  SET_PROP_CONST(PROP_TEXTURE_FORMAT_NUMBER);

  /* TEXTURE_GPU */
  SET_PROP_CONST(PROP_TEXTURE_GPU_TEXTURE_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_GPU_TEXTURE_UV_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_GPU_TEXTURE_U_POINTER);
  SET_PROP_CONST(PROP_TEXTURE_GPU_TEXTURE_V_POINTER);

  /* TEXTURE_HDR */
  SET_PROP_CONST(PROP_TEXTURE_HDR_HEADROOM_FLOAT);

  /* TEXTURE_HEIGHT */
  SET_PROP_CONST(PROP_TEXTURE_HEIGHT_NUMBER);

  /* TEXTURE_OPENGL */
  SET_PROP_CONST(PROP_TEXTURE_OPENGL_TEXTURE_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_OPENGL_TEXTURE_TARGET_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_OPENGL_TEXTURE_UV_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_OPENGL_TEXTURE_U_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_OPENGL_TEXTURE_V_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_OPENGL_TEX_H_FLOAT);
  SET_PROP_CONST(PROP_TEXTURE_OPENGL_TEX_W_FLOAT);

  /* TEXTURE_OPENGLES2 */
  SET_PROP_CONST(PROP_TEXTURE_OPENGLES2_TEXTURE_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_OPENGLES2_TEXTURE_TARGET_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_OPENGLES2_TEXTURE_UV_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_OPENGLES2_TEXTURE_U_NUMBER);
  SET_PROP_CONST(PROP_TEXTURE_OPENGLES2_TEXTURE_V_NUMBER);

  /* TEXTURE_SDR */
  SET_PROP_CONST(PROP_TEXTURE_SDR_WHITE_POINT_FLOAT);

  /* TEXTURE_VULKAN */
  SET_PROP_CONST(PROP_TEXTURE_VULKAN_TEXTURE_NUMBER);

  /* TEXTURE_WIDTH */
  SET_PROP_CONST(PROP_TEXTURE_WIDTH_NUMBER);

  /* THREAD_CREATE */
  SET_PROP_CONST(PROP_THREAD_CREATE_ENTRY_FUNCTION_POINTER);
  SET_PROP_CONST(PROP_THREAD_CREATE_NAME_STRING);
  SET_PROP_CONST(PROP_THREAD_CREATE_STACKSIZE_NUMBER);
  SET_PROP_CONST(PROP_THREAD_CREATE_USERDATA_POINTER);

  /* WINDOW_ANDROID */
  SET_PROP_CONST(PROP_WINDOW_ANDROID_SURFACE_POINTER);
  SET_PROP_CONST(PROP_WINDOW_ANDROID_WINDOW_POINTER);

  /* WINDOW_COCOA */
  SET_PROP_CONST(PROP_WINDOW_COCOA_METAL_VIEW_TAG_NUMBER);
  SET_PROP_CONST(PROP_WINDOW_COCOA_WINDOW_POINTER);

  /* WINDOW_CREATE */
  SET_PROP_CONST(PROP_WINDOW_CREATE_ALWAYS_ON_TOP_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_BORDERLESS_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_COCOA_VIEW_POINTER);
  SET_PROP_CONST(PROP_WINDOW_CREATE_COCOA_WINDOW_POINTER);
  SET_PROP_CONST(PROP_WINDOW_CREATE_CONSTRAIN_POPUP_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_EMSCRIPTEN_CANVAS_ID_STRING);
  SET_PROP_CONST(PROP_WINDOW_CREATE_EMSCRIPTEN_KEYBOARD_ELEMENT_STRING);
  SET_PROP_CONST(PROP_WINDOW_CREATE_EXTERNAL_GRAPHICS_CONTEXT_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_FLAGS_NUMBER);
  SET_PROP_CONST(PROP_WINDOW_CREATE_FOCUSABLE_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_FULLSCREEN_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_HEIGHT_NUMBER);
  SET_PROP_CONST(PROP_WINDOW_CREATE_HIDDEN_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_HIGH_PIXEL_DENSITY_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_MAXIMIZED_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_MENU_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_METAL_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_MINIMIZED_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_MODAL_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_MOUSE_GRABBED_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_OPENGL_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_PARENT_POINTER);
  SET_PROP_CONST(PROP_WINDOW_CREATE_RESIZABLE_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_TITLE_STRING);
  SET_PROP_CONST(PROP_WINDOW_CREATE_TOOLTIP_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_TRANSPARENT_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_UTILITY_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_VULKAN_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_WAYLAND_CREATE_EGL_WINDOW_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_WAYLAND_SURFACE_ROLE_CUSTOM_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_CREATE_WAYLAND_WL_SURFACE_POINTER);
  SET_PROP_CONST(PROP_WINDOW_CREATE_WIDTH_NUMBER);
  SET_PROP_CONST(PROP_WINDOW_CREATE_WIN32_HWND_POINTER);
  SET_PROP_CONST(PROP_WINDOW_CREATE_WIN32_PIXEL_FORMAT_HWND_POINTER);
  SET_PROP_CONST(PROP_WINDOW_CREATE_WINDOWSCENE_POINTER);
  SET_PROP_CONST(PROP_WINDOW_CREATE_X11_WINDOW_NUMBER);
  SET_PROP_CONST(PROP_WINDOW_CREATE_X_NUMBER);
  SET_PROP_CONST(PROP_WINDOW_CREATE_Y_NUMBER);

  /* WINDOW_EMSCRIPTEN */
  SET_PROP_CONST(PROP_WINDOW_EMSCRIPTEN_CANVAS_ID_STRING);
  SET_PROP_CONST(PROP_WINDOW_EMSCRIPTEN_KEYBOARD_ELEMENT_STRING);

  /* WINDOW_HDR */
  SET_PROP_CONST(PROP_WINDOW_HDR_ENABLED_BOOLEAN);
  SET_PROP_CONST(PROP_WINDOW_HDR_HEADROOM_FLOAT);

  /* WINDOW_KMSDRM */
  SET_PROP_CONST(PROP_WINDOW_KMSDRM_DEVICE_INDEX_NUMBER);
  SET_PROP_CONST(PROP_WINDOW_KMSDRM_DRM_FD_NUMBER);
  SET_PROP_CONST(PROP_WINDOW_KMSDRM_GBM_DEVICE_POINTER);

  /* WINDOW_OPENVR */
  SET_PROP_CONST(PROP_WINDOW_OPENVR_OVERLAY_ID_NUMBER);

  /* WINDOW_SDR */
  SET_PROP_CONST(PROP_WINDOW_SDR_WHITE_LEVEL_FLOAT);

  /* WINDOW_SHAPE */
  SET_PROP_CONST(PROP_WINDOW_SHAPE_POINTER);

  /* WINDOW_UIKIT */
  SET_PROP_CONST(PROP_WINDOW_UIKIT_METAL_VIEW_TAG_NUMBER);
  SET_PROP_CONST(PROP_WINDOW_UIKIT_OPENGL_FRAMEBUFFER_NUMBER);
  SET_PROP_CONST(PROP_WINDOW_UIKIT_OPENGL_RENDERBUFFER_NUMBER);
  SET_PROP_CONST(PROP_WINDOW_UIKIT_OPENGL_RESOLVE_FRAMEBUFFER_NUMBER);
  SET_PROP_CONST(PROP_WINDOW_UIKIT_WINDOW_POINTER);

  /* WINDOW_VIVANTE */
  SET_PROP_CONST(PROP_WINDOW_VIVANTE_DISPLAY_POINTER);
  SET_PROP_CONST(PROP_WINDOW_VIVANTE_SURFACE_POINTER);
  SET_PROP_CONST(PROP_WINDOW_VIVANTE_WINDOW_POINTER);

  /* WINDOW_WAYLAND */
  SET_PROP_CONST(PROP_WINDOW_WAYLAND_DISPLAY_POINTER);
  SET_PROP_CONST(PROP_WINDOW_WAYLAND_EGL_WINDOW_POINTER);
  SET_PROP_CONST(PROP_WINDOW_WAYLAND_SURFACE_POINTER);
  SET_PROP_CONST(PROP_WINDOW_WAYLAND_VIEWPORT_POINTER);
  SET_PROP_CONST(PROP_WINDOW_WAYLAND_XDG_POPUP_POINTER);
  SET_PROP_CONST(PROP_WINDOW_WAYLAND_XDG_POSITIONER_POINTER);
  SET_PROP_CONST(PROP_WINDOW_WAYLAND_XDG_SURFACE_POINTER);
  SET_PROP_CONST(PROP_WINDOW_WAYLAND_XDG_TOPLEVEL_EXPORT_HANDLE_STRING);
  SET_PROP_CONST(PROP_WINDOW_WAYLAND_XDG_TOPLEVEL_POINTER);

  /* WINDOW_WIN32 */
  SET_PROP_CONST(PROP_WINDOW_WIN32_HDC_POINTER);
  SET_PROP_CONST(PROP_WINDOW_WIN32_HWND_POINTER);
  SET_PROP_CONST(PROP_WINDOW_WIN32_INSTANCE_POINTER);

  /* WINDOW_X11 */
  SET_PROP_CONST(PROP_WINDOW_X11_DISPLAY_POINTER);
  SET_PROP_CONST(PROP_WINDOW_X11_SCREEN_NUMBER);
  SET_PROP_CONST(PROP_WINDOW_X11_WINDOW_NUMBER);
}

#undef SET_PROP_CONST
#undef SET_INIT_CONST
#undef SET_U32_CONST
