local test = require("test")
local sdl3 = require("sdl3")

test.case("sdl3 exposes time-related SDL APIs", function()
   test.equal(type(sdl3.GetCurrentTime), "function")
   test.equal(type(sdl3.GetTicks), "function")
   test.equal(type(sdl3.GetTicksNS), "function")
   test.equal(type(sdl3.GetPerformanceCounter), "function")
   test.equal(type(sdl3.GetPerformanceFrequency), "function")
   test.equal(type(sdl3.Delay), "function")
   test.equal(type(sdl3.DelayNS), "function")
   test.equal(type(sdl3.DelayPrecise), "function")
end)

test.case("sdl3 exposes SDL renderer drawing APIs", function()
   test.equal(type(sdl3.SetRenderDrawColor), "function")
   test.equal(type(sdl3.RenderClear), "function")
   test.equal(type(sdl3.RenderPoint), "function")
   test.equal(type(sdl3.RenderLine), "function")
   test.equal(type(sdl3.RenderFillRect), "function")
   test.equal(type(sdl3.get_renderer), "function")
end)

test.case("sdl3 exposes mouse event constants", function()
   test.truthy(type(sdl3.EVENT_MOUSE_MOTION) == "number")
   test.truthy(type(sdl3.EVENT_MOUSE_BUTTON_DOWN) == "number")
   test.truthy(type(sdl3.EVENT_MOUSE_BUTTON_UP) == "number")
   test.truthy(type(sdl3.BUTTON_LEFT) == "number")
   test.truthy(type(sdl3.BUTTON_MIDDLE) == "number")
   test.truthy(type(sdl3.BUTTON_RIGHT) == "number")
   test.equal(type(sdl3.GetMouseState), "function")
end)
