local test = require("test")
local sdl3 = require("sdl3")

test.case("sdl3 exposes time-related SDL APIs", function()
   test.equal(type(sdl3.GetCurrentTime), "function")
   test.equal(type(sdl3.GetTicks), "function")
   test.equal(type(sdl3.GetTicksNS), "function")
   test.equal(type(sdl3.GetPerformanceCounter), "function")
   test.equal(type(sdl3.GetPerformanceFrequency), "function")
   test.equal(type(sdl3.Delay), "function")
   test.equal(type(sdl3.DelayNS), "function")
   test.equal(type(sdl3.DelayPrecise), "function")
end)

test.case("sdl3 exposes thread-priority SDL APIs", function()
   test.equal(type(sdl3.SetCurrentThreadPriority), "function")
   test.truthy(type(sdl3.THREAD_PRIORITY_LOW) == "number")
   test.truthy(type(sdl3.THREAD_PRIORITY_NORMAL) == "number")
   test.truthy(type(sdl3.THREAD_PRIORITY_HIGH) == "number")
   test.truthy(type(sdl3.THREAD_PRIORITY_TIME_CRITICAL) == "number")
   test.equal(type(sdl3.HINT_THREAD_PRIORITY_POLICY), "string")
end)

test.case("sdl3 exposes SDL renderer drawing APIs", function()
   test.equal(type(sdl3.SetRenderDrawColor), "function")
   test.equal(type(sdl3.RenderClear), "function")
   test.equal(type(sdl3.RenderPoint), "function")
   test.equal(type(sdl3.RenderLine), "function")
   test.equal(type(sdl3.RenderFillRect), "function")
   test.equal(type(sdl3.CreateTexture), "function")
   test.equal(type(sdl3.UpdateTexture), "function")
   test.equal(type(sdl3.SetTextureColorMod), "function")
   test.equal(type(sdl3.SetTextureAlphaMod), "function")
   test.equal(type(sdl3.SetTextureBlendMode), "function")
   test.equal(type(sdl3.RenderTexture), "function")
   test.equal(type(sdl3.DestroyTexture), "function")
end)

test.case("sdl3 exposes renderer texture constants", function()
   test.truthy(type(sdl3.PIXELFORMAT_RGBA8888) == "number")
   test.truthy(type(sdl3.PIXELFORMAT_RGBA32) == "number")
   test.truthy(type(sdl3.TEXTUREACCESS_STATIC) == "number")
   test.truthy(type(sdl3.TEXTUREACCESS_STREAMING) == "number")
   test.truthy(type(sdl3.TEXTUREACCESS_TARGET) == "number")
   test.truthy(type(sdl3.BLENDMODE_NONE) == "number")
   test.truthy(type(sdl3.BLENDMODE_BLEND) == "number")
   test.truthy(type(sdl3.BLENDMODE_ADD) == "number")
   test.truthy(type(sdl3.BLENDMODE_MOD) == "number")
   test.truthy(type(sdl3.BLENDMODE_MUL) == "number")
end)

test.case("sdl3 exposes mouse event constants", function()
   test.truthy(type(sdl3.EVENT_MOUSE_MOTION) == "number")
   test.truthy(type(sdl3.EVENT_MOUSE_BUTTON_DOWN) == "number")
   test.truthy(type(sdl3.EVENT_MOUSE_BUTTON_UP) == "number")
   test.truthy(type(sdl3.EVENT_WINDOW_RESIZED) == "number")
   test.truthy(type(sdl3.EVENT_WINDOW_PIXEL_SIZE_CHANGED) == "number")
   test.truthy(type(sdl3.BUTTON_LEFT) == "number")
   test.truthy(type(sdl3.BUTTON_MIDDLE) == "number")
   test.truthy(type(sdl3.BUTTON_RIGHT) == "number")
   test.equal(type(sdl3.GetMouseState), "function")
   test.equal(type(sdl3.GetWindowSize), "function")
   test.equal(type(sdl3.GetWindowSizeInPixels), "function")
end)
