if(NOT DEFINED INPUT)
    message(FATAL_ERROR "INPUT is required")
endif()

if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR "OUTPUT is required")
endif()

if(NOT DEFINED SYMBOL)
    message(FATAL_ERROR "SYMBOL is required")
endif()

file(READ "${INPUT}" LUA_HEX HEX)
string(LENGTH "${LUA_HEX}" HEX_LEN)
math(EXPR BYTE_COUNT "${HEX_LEN} / 2")

set(BYTES "")
if(BYTE_COUNT GREATER 0)
    math(EXPR LAST_INDEX "${BYTE_COUNT} - 1")
    foreach(I RANGE 0 ${LAST_INDEX})
        math(EXPR OFFSET "${I} * 2")
        string(SUBSTRING "${LUA_HEX}" ${OFFSET} 2 HEX_BYTE)
        string(APPEND BYTES "0x${HEX_BYTE},")
        math(EXPR COL "${I} % 12")
        if(COL EQUAL 11)
            string(APPEND BYTES "\n    ")
        else()
            string(APPEND BYTES " ")
        endif()
    endforeach()
endif()

file(WRITE "${OUTPUT}" "/* Generated file. Do not edit. */\n")
file(APPEND "${OUTPUT}" "#include <stddef.h>\n\n")
file(APPEND "${OUTPUT}" "const unsigned char ${SYMBOL}[] = {\n    ${BYTES}\n};\n")
file(APPEND "${OUTPUT}" "const size_t ${SYMBOL}_len = ${BYTE_COUNT};\n")
